# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home_frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 450)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 450))
        MainWindow.setMaximumSize(QtCore.QSize(800, 450))
        font = QtGui.QFont()
        font.setPointSize(16)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.OptionsButton = QtWidgets.QPushButton(self.centralwidget)
        self.OptionsButton.setGeometry(QtCore.QRect(220, 230, 350, 50))
        self.OptionsButton.setObjectName("OptionsButton")
        self.SensorTestButton = QtWidgets.QPushButton(self.centralwidget)
        self.SensorTestButton.setGeometry(QtCore.QRect(220, 90, 350, 50))
        self.SensorTestButton.setObjectName("SensortTestButton")
        self.ExerciseButton = QtWidgets.QPushButton(self.centralwidget)
        self.ExerciseButton.setGeometry(QtCore.QRect(220, 160, 350, 50))
        self.ExerciseButton.setObjectName("ExerciseButton")
        self.QuitButton = QtWidgets.QPushButton(self.centralwidget)
        self.QuitButton.setGeometry(QtCore.QRect(220, 290, 350, 50))
        self.QuitButton.setObjectName("QuitButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Human Balance System"))
        self.OptionsButton.setStatusTip(_translate("MainWindow", "quit the application"))
        self.OptionsButton.setText(_translate("MainWindow", "options"))
        self.SensorTestButton.setStatusTip(_translate("MainWindow", "open test page"))
        self.SensorTestButton.setText(_translate("MainWindow", "Sensory Test"))
        self.ExerciseButton.setStatusTip(_translate("MainWindow", "open exercise page"))
        self.ExerciseButton.setText(_translate("MainWindow", "Exercise"))
        self.QuitButton.setStatusTip(_translate("MainWindow", "quit the application"))
        self.QuitButton.setText(_translate("MainWindow", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.showFullScreen()
    sys.exit(app.exec_())
