# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainFrame.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import os
from Home_Frame import Ui_MainWindow
from Exercise_Frame import Exercise_Frame
from Steper_Adjust import StepperAdjustFrame
from control_motor_gui import MotorControlUi
from sensoryFramePro import Ui_sensoryFramePro


class Ui_mainFramePro(object):
    def setupUi(self, mainFrame):
        mainFrame.setObjectName("mainFrame")
        mainFrame.resize(800, 470)
        mainFrame.setStyleSheet("background-color: #141332;")
        self.SensorTestButton = QtWidgets.QPushButton(mainFrame)
        self.SensorTestButton.setGeometry(QtCore.QRect(90, 50, 631, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.SensorTestButton.setFont(font)
        self.SensorTestButton.setStyleSheet("QPushButton {\n"
                                            "    background-color: #6359E9; /* Change this to your desired background color */\n"
                                            "    color: white; /* Change this to your desired text color */\n"
                                            "    border: 2px; /* Change this to your desired border color and thickness */\n"
                                            "    border-radius: 15px; /* Adjust the radius to your desired value for rounded corners */\n"
                                            "    padding: 5px 10px; /* Adjust the padding to your desired value */\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:hover {\n"
                                            "    background-color: #0ACDE4; /* Change this to your desired background color on hover */\n"
                                            "    border: 2px solid #0ACDE4; /* Change this to your desired border color on hover */\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:pressed {\n"
                                            "    background-color: #0AADE2; /* Change this to your desired background color when pressed */\n"
                                            "    border: 2px solid #0AADE2; /* Change this to your desired border color when pressed */\n"
                                            "}")
        self.SensorTestButton.setObjectName("SensorTestButton")
        self.pushButton_2 = QtWidgets.QPushButton(mainFrame)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 140, 631, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
                                        "    background-color: #6359E9; /* Change this to your desired background color */\n"
                                        "    color: white; /* Change this to your desired text color */\n"
                                        "    border: 2px; /* Change this to your desired border color and thickness */\n"
                                        "    border-radius: 15px; /* Adjust the radius to your desired value for rounded corners */\n"
                                        "    padding: 5px 10px; /* Adjust the padding to your desired value */\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: #0ACDE4; /* Change this to your desired background color on hover */\n"
                                        "    border: 2px solid #0ACDE4; /* Change this to your desired border color on hover */\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    background-color: #0AADE2; /* Change this to your desired background color when pressed */\n"
                                        "    border: 2px solid #0AADE2; /* Change this to your desired border color when pressed */\n"
                                        "}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.ExerciseButton = QtWidgets.QPushButton(mainFrame)
        self.ExerciseButton.setGeometry(QtCore.QRect(90, 220, 631, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ExerciseButton.setFont(font)
        self.ExerciseButton.setStyleSheet("QPushButton {\n"
                                          "    background-color: #6359E9; /* Change this to your desired background color */\n"
                                          "    color: white; /* Change this to your desired text color */\n"
                                          "    border: 2px; /* Change this to your desired border color and thickness */\n"
                                          "    border-radius: 15px; /* Adjust the radius to your desired value for rounded corners */\n"
                                          "    padding: 5px 10px; /* Adjust the padding to your desired value */\n"
                                          "}\n"
                                          "\n"
                                          "QPushButton:hover {\n"
                                          "    background-color: #0ACDE4; /* Change this to your desired background color on hover */\n"
                                          "    border: 2px solid #0ACDE4; /* Change this to your desired border color on hover */\n"
                                          "}\n"
                                          "\n"
                                          "QPushButton:pressed {\n"
                                          "    background-color: #0AADE2; /* Change this to your desired background color when pressed */\n"
                                          "    border: 2px solid #0AADE2; /* Change this to your desired border color when pressed */\n"
                                          "}")
        self.ExerciseButton.setObjectName("ExerciseButton")
        self.OptionsButton = QtWidgets.QPushButton(mainFrame)
        self.OptionsButton.setGeometry(QtCore.QRect(90, 310, 631, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.OptionsButton.setFont(font)
        self.OptionsButton.setStyleSheet("QPushButton {\n"
                                         "    background-color: #6359E9; /* Change this to your desired background color */\n"
                                         "    color: white; /* Change this to your desired text color */\n"
                                         "    border: 2px; /* Change this to your desired border color and thickness */\n"
                                         "    border-radius: 15px; /* Adjust the radius to your desired value for rounded corners */\n"
                                         "    padding: 5px 10px; /* Adjust the padding to your desired value */\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:hover {\n"
                                         "    background-color: #0ACDE4; /* Change this to your desired background color on hover */\n"
                                         "    border: 2px solid #0ACDE4; /* Change this to your desired border color on hover */\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:pressed {\n"
                                         "    background-color: #0AADE2; /* Change this to your desired background color when pressed */\n"
                                         "    border: 2px solid #0AADE2; /* Change this to your desired border color when pressed */\n"
                                         "}")
        self.OptionsButton.setObjectName("OptionsButton")
        self.QuitButton = QtWidgets.QPushButton(mainFrame)
        self.QuitButton.setGeometry(QtCore.QRect(60, 400, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.QuitButton.setFont(font)
        self.QuitButton.setStyleSheet("QPushButton {\n"
                                      "    background-color: #6359E9; /* Change this to your desired background color */\n"
                                      "    color: white; /* Change this to your desired text color */\n"
                                      "    border: 2px; /* Change this to your desired border color and thickness */\n"
                                      "    border-radius: 15px; /* Adjust the radius to your desired value for rounded corners */\n"
                                      "    padding: 5px 10px; /* Adjust the padding to your desired value */\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover {\n"
                                      "    background-color: #0ACDE4; /* Change this to your desired background color on hover */\n"
                                      "    border: 2px solid #0ACDE4; /* Change this to your desired border color on hover */\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:pressed {\n"
                                      "    background-color: #0AADE2; /* Change this to your desired background color when pressed */\n"
                                      "    border: 2px solid #0AADE2; /* Change this to your desired border color when pressed */\n"
                                      "}")
        self.QuitButton.setObjectName("QuitButton")

        self.retranslateUi(mainFrame)
        QtCore.QMetaObject.connectSlotsByName(mainFrame)

    def retranslateUi(self, mainFrame):
        _translate = QtCore.QCoreApplication.translate
        mainFrame.setWindowTitle(_translate("mainFrame", "Frame"))
        self.SensorTestButton.setText(_translate("mainFrame", "SENSORY TEST"))
        self.pushButton_2.setText(_translate(
            "mainFrame", "LIMIT OF STABILITY"))
        self.ExerciseButton.setText(_translate("mainFrame", "EXERCISE"))
        self.OptionsButton.setText(_translate("mainFrame", "OPTIONS"))
        self.QuitButton.setText(_translate("mainFrame", "QUIT"))


if os.environ.get('DISPLAY', '') == '':
    print('no display found. Using :0.0')
    os.environ.__setitem__('DISPLAY', ':0.0')


class MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()

        self.ui = Ui_mainFramePro()
        self.ui.setupUi(self)

        # Connect buttons to their respective functions
        self.ui.QuitButton.clicked.connect(self.close)  # Quit Button
        self.ui.SensorTestButton.clicked.connect(
            self.open_sensory_page)  # Sensory Test Button
        self.ui.ExerciseButton.clicked.connect(
            self.open_exercise_page)  # Exercises Button
        self.ui.OptionsButton.clicked.connect(
            self.open_option_page)  # Options Button

    def open_sensory_page(self):
        self.sensory_page = QtWidgets.QMainWindow()
        self.ui = Ui_sensoryFramePro()
        self.ui.setupUi(self.sensory_page)
        self.sensory_page.showFullScreen()

    def open_exercise_page(self):
        self.exercise_page = QtWidgets.QMainWindow()
        self.ui = Exercise_Frame()
        self.ui.setupUi(self.exercise_page)
        self.exercise_page.show()

    def open_option_page(self):
        self.option_page = QtWidgets.QMainWindow()
        self.ui = MotorControlUi()
        self.ui.setupUi(self.option_page)
        self.option_page.showFullScreen()
