# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sensoryFrame.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5.QtWidgets import QVBoxLayout
import pyqtgraph as pg
from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg
from HomeFramePro import Ui_MainWindow
from live_plot_module.live_plot import LivePlot
from sensory_model import SensoryModel

class Ui_sensoryFramePro(object):
    def setupUi(self, sensoryFrame):
        self.model=SensoryModel()
        sensoryFrame.setObjectName("sensoryFrame")
        sensoryFrame.resize(800, 470)
        sensoryFrame.setStyleSheet("background-color: #141332;")
        self.backButton = QtWidgets.QPushButton(sensoryFrame)
        self.backButton.setGeometry(QtCore.QRect(30, 390, 151, 31))
        self.backButton.setStyleSheet("QPushButton {\n"
"    background-color: #6359E9; /* Change this to your desired background color */\n"
"    color: white; /* Change this to your desired text color */\n"
"    border: 2px; /* Change this to your desired border color and thickness */\n"
"    border-radius: 15px; /* Adjust the radius to your desired value for rounded corners */\n"
"    padding: 5px 10px; /* Adjust the padding to your desired value */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0ACDE4; /* Change this to your desired background color on hover */\n"
"    border: 2px solid #0ACDE4; /* Change this to your desired border color on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0AADE2; /* Change this to your desired background color when pressed */\n"
"    border: 2px solid #0AADE2; /* Change this to your desired border color when pressed */\n"
"}")
        self.backButton.setObjectName("pushButton_2")
        self.frame = QtWidgets.QFrame(sensoryFrame)
        self.frame.setGeometry(QtCore.QRect(20, 50, 361, 291))
        self.frame.setStyleSheet("background-color:#1D1D41;\n"
"border-radius: 15px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_13 = QtWidgets.QFrame(self.frame)
        self.frame_13.setGeometry(QtCore.QRect(10, 9, 341, 241))
        self.frame_13.setStyleSheet("background-color:#8C89B4;\n"
"border-radius: 15px;")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.frame_22 = QtWidgets.QFrame(self.frame)
        self.frame_22.setGeometry(QtCore.QRect(20, 260, 71, 20))
        self.frame_22.setStyleSheet("background-color:#64CFF6;\n"
"border-radius: 30px;")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.label_10 = QtWidgets.QLabel(self.frame_22)
        self.label_10.setGeometry(QtCore.QRect(20, 0, 47, 16))
        self.label_10.setStyleSheet("QLabel {\n"
"    color: #ffffff; /* Change this to your desired text color */\n"
"    font-family: Arial; /* Change this to your desired font family */\n"
"    font-size: 12px; /* Change this to your desired font size */\n"
"    font-weight: bold; /* Make the text bold */\n"
"    /* Add other text properties as needed */\n"
"}")
        self.label_10.setObjectName("label_10")
        self.frame_23 = QtWidgets.QFrame(self.frame)
        self.frame_23.setGeometry(QtCore.QRect(100, 260, 71, 20))
        self.frame_23.setStyleSheet("background-color:#8C89B4;\n"
"border-radius: 30px;")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.label_12 = QtWidgets.QLabel(self.frame_23)
        self.label_12.setGeometry(QtCore.QRect(20, 0, 47, 16))
        self.label_12.setStyleSheet("QLabel {\n"
"    color: #ffffff; /* Change this to your desired text color */\n"
"    font-family: Arial; /* Change this to your desired font family */\n"
"    font-size: 12px; /* Change this to your desired font size */\n"
"    font-weight: bold; /* Make the text bold */\n"
"    /* Add other text properties as needed */\n"
"}")
        self.label_12.setObjectName("label_12")
        self.frame_24 = QtWidgets.QFrame(self.frame)
        self.frame_24.setGeometry(QtCore.QRect(180, 260, 71, 20))
        self.frame_24.setStyleSheet("background-color:#8C89B4;\n"
"border-radius: 30px;")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.label_13 = QtWidgets.QLabel(self.frame_24)
        self.label_13.setGeometry(QtCore.QRect(20, 0, 47, 16))
        self.label_13.setStyleSheet("QLabel {\n"
"    color: #ffffff; /* Change this to your desired text color */\n"
"    font-family: Arial; /* Change this to your desired font family */\n"
"    font-size: 12px; /* Change this to your desired font size */\n"
"    font-weight: bold; /* Make the text bold */\n"
"    /* Add other text properties as needed */\n"
"}")
        self.label_13.setObjectName("label_13")
        self.frame_25 = QtWidgets.QFrame(self.frame)
        self.frame_25.setGeometry(QtCore.QRect(260, 260, 71, 20))
        self.frame_25.setStyleSheet("background-color:#8C89B4;\n"
"border-radius: 30px;")
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.label_14 = QtWidgets.QLabel(self.frame_25)
        self.label_14.setGeometry(QtCore.QRect(20, 0, 47, 16))
        self.label_14.setStyleSheet("QLabel {\n"
"    color: #ffffff; /* Change this to your desired text color */\n"
"    font-family: Arial; /* Change this to your desired font family */\n"
"    font-size: 12px; /* Change this to your desired font size */\n"
"    font-weight: bold; /* Make the text bold */\n"
"    /* Add other text properties as needed */\n"
"}")
        self.label_14.setObjectName("label_14")
        self.frame_2 = QtWidgets.QFrame(sensoryFrame)
        self.frame_2.setGeometry(QtCore.QRect(410, 50, 371, 291))
        self.frame_2.setStyleSheet("background-color:#1D1D41;\n"
"border-radius: 15px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_x = QtWidgets.QFrame(self.frame_2)
        self.frame_x.setGeometry(QtCore.QRect(190, 170, 171, 101))
        self.frame_x.setStyleSheet("background-color:#8C89B4;\n"
"border-radius: 15px;")
        self.frame_x.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_x.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_x.setObjectName("frame_x")
        self.frame_y = QtWidgets.QFrame(self.frame_2)
        self.frame_y.setGeometry(QtCore.QRect(10, 170, 171, 101))
        self.frame_y.setStyleSheet("background-color:#8C89B4;\n"
"border-radius: 15px;")
        self.frame_y.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_y.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_y.setObjectName("frame_y")
        self.frame_28 = QtWidgets.QFrame(self.frame_2)
        self.frame_28.setGeometry(QtCore.QRect(140, 10, 221, 151))
        self.frame_28.setStyleSheet("background-color:#8C89B4;\n"
"border-radius: 15px;")
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.frame_29 = QtWidgets.QFrame(self.frame_2)
        self.frame_29.setGeometry(QtCore.QRect(10, 10, 121, 151))
        self.frame_29.setStyleSheet("background-color:#8C89B4;\n"
"border-radius: 15px;")
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.pushButton = QtWidgets.QPushButton(sensoryFrame)
        self.pushButton.setGeometry(QtCore.QRect(620, 392, 151, 31))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #6359E9; /* Change this to your desired background color */\n"
"    color: white; /* Change this to your desired text color */\n"
"    border: 2px; /* Change this to your desired border color and thickness */\n"
"    border-radius: 15px; /* Adjust the radius to your desired value for rounded corners */\n"
"    padding: 5px 10px; /* Adjust the padding to your desired value */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0ACDE4; /* Change this to your desired background color on hover */\n"
"    border: 2px solid #0ACDE4; /* Change this to your desired border color on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0AADE2; /* Change this to your desired background color when pressed */\n"
"    border: 2px solid #0AADE2; /* Change this to your desired border color when pressed */\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_15 = QtWidgets.QLabel(sensoryFrame)
        self.label_15.setGeometry(QtCore.QRect(300, 389, 81, 31))
        self.label_15.setStyleSheet("QLabel {\n"
"    color: #ffffff; /* Change this to your desired text color */\n"
"    font-family: Arial; /* Change this to your desired font family */\n"
"    font-size: 12px; /* Change this to your desired font size */\n"
"    font-weight: bold; /* Make the text bold */\n"
"    /* Add other text properties as needed */\n"
"}")
        self.label_15.setObjectName("label_15")
        self.progressBar = QtWidgets.QProgressBar(sensoryFrame)
        self.progressBar.setGeometry(QtCore.QRect(20, 352, 761, 21))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    border: 1px solid grey ;\n"
"    border-radius: 300px;\n"
"    text-align: center;\n"
"    background-color:#1D1D41;\n"
"    color: #ffffff;\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"    \n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #64CFF6; /* Change this color to your desired color */\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.frame_30 = QtWidgets.QFrame(sensoryFrame)
        self.frame_30.setGeometry(QtCore.QRect(410, 389, 141, 31))
        self.frame_30.setStyleSheet("background-color:#8C89B4;\n"
"border-radius: 30px;")
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.label_16 = QtWidgets.QLabel(self.frame_30)
        self.label_16.setGeometry(QtCore.QRect(30, 0, 81, 31))
        self.label_16.setStyleSheet("QLabel {\n"
"    color: #ffffff; /* Change this to your desired text color */\n"
"    font-family: Arial; /* Change this to your desired font family */\n"
"    font-size: 12px; /* Change this to your desired font size */\n"
"    font-weight: bold; /* Make the text bold */\n"
"    /* Add other text properties as needed */\n"
"}")
        self.label_16.setObjectName("label_16")
######## setup Liveplot
        winX=pg.GraphicsLayoutWidget()
        layoutx = QVBoxLayout()
        self.frame_x.setLayout(layoutx)
        layoutx.addWidget(winX)
        winY=pg.GraphicsLayoutWidget()
        layoutY = QVBoxLayout()
        self.frame_y.setLayout(layoutY)
        layoutY.addWidget(winY)
        self.livePlotX=LivePlot(win=winX,row=0,col=0)
        self.livePlotY=LivePlot(win=winY,row=0,col=0)
#######end of setup liveplot
        self.retranslateUi(sensoryFrame)
        QtCore.QMetaObject.connectSlotsByName(sensoryFrame)
#################### end of gui setup
#################### buttons function connect section  
        self.backButton.clicked.connect(self.go_to_home)
#################### end of buttton function connect section 
#################### time loop setup
        self.timer = pg.QtCore.QTimer()
        self.timer.timeout.connect(self.update)
        self.timer.start(10) 
################### end of time loop setup
################## time update loop 
    def update(self):
        self.model.updateLoop()
        sensorX=self.model.getSensorX()
        sensorY=self.model.getSensorY()
        self.livePlotX.update(sensorX)
        self.livePlotY.update(sensorY)
################# end of update loop 


    def retranslateUi(self, sensoryFrame):
        _translate = QtCore.QCoreApplication.translate
        sensoryFrame.setWindowTitle(_translate("sensoryFrame", "Frame"))
        self.backButton.setText(_translate("sensoryFrame", "back "))
        self.label_10.setText(_translate("sensoryFrame", "test 1"))
        self.label_12.setText(_translate("sensoryFrame", "test 2"))
        self.label_13.setText(_translate("sensoryFrame", "test 3"))
        self.label_14.setText(_translate("sensoryFrame", "test 4"))
        self.pushButton.setText(_translate("sensoryFrame", "start and stop button"))
        self.label_15.setText(_translate("sensoryFrame", "fixed paltform"))
        self.label_16.setText(_translate("sensoryFrame", "free platform"))

    def go_to_home(self):
        self.timer.stop()
        # Close the current window (Exercise_Frame) and show the main window (Home_Frame)
        main_window = self.backButton.window()  # Access the parent window
        while main_window is not None and not isinstance(main_window, QtWidgets.QMainWindow):
            main_window = main_window.parent()
        if main_window is not None:
            home_frame = Ui_MainWindow()  # Instantiate the home frame
            # Set up the home frame in the main window
            home_frame.setupUi(main_window)
            main_window.show()  # Show the main window
            main_window.close()
          # Close the current window
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    sensoryFrame = QtWidgets.QFrame()
    ui = Ui_sensoryFramePro()
    ui.setupUi(sensoryFrame)
    sensoryFrame.show()
    sys.exit(app.exec_())
