# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stepper_adjust_frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton, QVBoxLayout, QFrame, QStackedWidget,QWidget


class StepperAdjustFrame(QWidget):
    def setup(self, frame)->None:
        frame.setObjectName("steperAdjust")
        frame.resize(801, 600)
        self.centralwidget = QtWidgets.QWidget(frame)
        self.centralwidget.setObjectName("centralwidget")
        self.UpButton = QtWidgets.QPushButton(self.centralwidget)
        self.UpButton.setGeometry(QtCore.QRect(120, 250, 271, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.UpButton.setFont(font)
        self.UpButton.setObjectName("UpButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(440, 250, 251, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        frame.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(frame)
        self.statusbar.setObjectName("statusbar")
        frame.setStatusBar(self.statusbar)

        self.retranslateUi(frame)
        QtCore.QMetaObject.connectSlotsByName(frame)

    def retranslateUi(self, steperAdjust):
        _translate = QtCore.QCoreApplication.translate
        steperAdjust.setWindowTitle(_translate("steperAdjust", "stepper adjust "))
        self.UpButton.setText(_translate("steperAdjust", "up"))
        self.pushButton_2.setText(_translate("steperAdjust", "down"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    steperAdjust = QtWidgets.QMainWindow()
    ui = StepperAdjustFrame()
    ui.setupUi(steperAdjust)
    steperAdjust.show()
    sys.exit(app.exec_())
